from __future__ import annotations

from pathlib import Path

PIPELINE_DIR = Path(__file__).resolve().parents[1]
REPO_ROOT = PIPELINE_DIR.parents[1]

DATA_PATH = REPO_ROOT / "data" / "processed" / "12h_features_indicators_with_ohlcv.csv"

OUTPUTS_DIR = PIPELINE_DIR / "outputs"
FIGURES_DIR = PIPELINE_DIR / "figures"
ARTIFACTS_DIR = PIPELINE_DIR / "artifacts"
REPORT_PATH = PIPELINE_DIR / "report.md"

RANDOM_SEED = 42

FEATURE_SHIFT = 1

N_SPLITS = 4
MIN_TRAIN_SIZE = 0.5
TEST_SIZE = 0.1
FOLD_STEP_SIZE = None

CLIP_QUANTILES = (0.01, 0.99)
USE_PCA = False
PCA_N_COMPONENTS = 0.95

HMM_KS = [2, 3, 4, 5, 6]
HMM_SEEDS = [0, 1, 2]
HMM_MAX_ITER = 200
HMM_COV_TYPE = "full"
HMM_VAL_RATIO = 0.2
HMM_MIN_STATE_FRAC = 0.07
HMM_MIN_AVG_DURATION = 3
HMM_STABLE_FRACTION = 0.5

GMM_KS = [2, 3, 4, 5, 6]
GMM_SEEDS = [0, 1, 2]
GMM_MAX_ITER = 200
GMM_COV_TYPE = "full"

ENTROPY_MAX = 1.0

MIN_ACTION_RATE = 0.10
MIN_PURITY = 0.60
MIN_DURATION = 3
MAX_LEAVE_PROB = 0.35

ELIGIBILITY_PROB_THRESHOLD = 0.8
USE_ELIGIBILITY_CLASSIFIER = True

DECISION_THRESHOLD = 0.95

SWEEP_ACTION_RATES = [0.05, 0.08, 0.10, 0.12]
SWEEP_PURITY = [0.5, 0.55, 0.6, 0.65]
